export const vizConfig = {
  id: 'gauge',
  label: 'Gauge Visualization',
  options: {
    // PLOT ADVANCED
    bar_arm_length: {
      type: 'number',
      label: 'Arm Length',
      default: 9,
      section: 'Plot',
      display: 'range',
      min: 0,
      max: 50,
      step: 0.5,
      order: 200,
      display_size: 'half',
    },
    bar_arm_weight: {
      type: 'number',
      label: 'Thickness',
      default: 48,
      section: 'Plot',
      display: 'range',
      min: 0,
      max: 100,
      order: 300,
      display_size: 'half',
    },
    bar_spinner_length: {
      type: 'number',
      label: 'Pointer Length',
      default: 121,
      section: 'Plot',
      display: 'range',
      min: 0,
      max: 200,
      order: 400,
      display_size: 'half',
    },
    bar_spinner_weight: {
      type: 'number',
      label: 'Thickness',
      default: 25,
      section: 'Plot',
      display: 'range',
      min: 0,
      max: 100,
      default: 25,
      order: 500,
      display_size: 'half',
    },

    // PLOT
    bar_style: {
      type: 'string',
      label: 'Gauge Type',
      display: 'select',
      section: 'Plot',
      values: [{Vertical: 'vertical'}, {Horizontal: 'horizontal'}],
      default: 'vertical',
      order: 0,
    },
    bar_range_min: {
      type: 'number',
      label: 'Range Min Override',
      section: 'Plot',
      order: 30,
      default: 0,
      display_size: 'half',
    },
    bar_range_max: {
      type: 'number',
      label: 'Range Max Override',
      section: 'Plot',
      order: 31,
      default: 100.701,
      display_size: 'half',
    },
    bar_value_label_type: {
      type: 'string',
      label: 'Value Label Type',
      display: 'select',
      section: 'Value',
      values: [
        {'Value and Measure Label': 'both'},
        {'Value and Dimension': 'dboth'},
        {'Only Value': 'value'},
        {'Only Label': 'label'},
        {'Only Dimension': 'dim'},
        {None: 'none'},
      ],
      default: 'both',
      order: 40,
    },
    bar_value_label_font: {
      type: 'number',
      label: 'Value Label Font Size',
      section: 'Value',
      default: 8,
      order: 50,
    },
    bar_value_formatting: {
      type: 'string',
      label: 'Value Formatting Override',
      section: 'Value',
      order: 51,
    },
    bar_value_label_override: {
      type: 'string',
      label: 'Value Label Override',
      section: 'Value',
      order: 60,
    },
    bar_value_label_padding: {
      type: 'number',
      label: 'Value Label Padding',
      default: 45,
      section: 'Value',
      display: 'range',
      min: 0,
      max: 120,
      order: 70,
    },
    bar_target_source: {
      type: 'string',
      label: 'Target Source',
      display: 'select',
      section: 'Target',
      values: [
        {'First Measure': 'first'},
        {'Second Measure': 'second'},
        {Override: 'override'},
        {'No Target': 'off'},
      ],
      default: 'off',
      order: 80,
    },
    bar_target_label_type: {
      type: 'string',
      label: 'Target Label Type',
      display: 'select',
      section: 'Target',
      values: [
        {'Value and Label': 'both'},
        {'Only Value': 'value'},
        {'Only Label': 'label'},
        {'Value and Dimension': 'dboth'},
        {'Only Dimension': 'dim'},
        {'No Label': 'nolabel'},
      ],
      default: 'none',
      order: 90,
    },
    bar_target_label_font: {
      type: 'number',
      label: 'Target Label Font Size',
      section: 'Target',
      default: 3,
      order: 100,
    },
    bar_target_label_override: {
      type: 'string',
      label: 'Target Label Override',
      section: 'Target',
      order: 120,
    },
    bar_target_value_override: {
      type: 'string',
      label: 'Target Value Override',
      section: 'Target',
      order: 110,
    },
    bar_target_value_format: {
      type: 'string',
      label: 'Target Value Formatting',
      section: 'Target',
      order: 120,
    },
    bar_label_font_size: {
      type: 'number',
      label: 'Range Label Font Size',
      section: 'Plot',
      default: 3,
      order: 140,
    },
    bar_range_formatting: {
      type: 'string',
      label: 'Range Label Value Formatting',
      section: 'Plot',
      order: 150,
    },

    // STYLE
    bar_fill_color: {
      type: 'string',
      label: 'Gauge Fill Color',
      section: 'Style',
      display: 'color',
      default: '#0092E5',
      order: 10,
    },
    bar_background_color: {
      type: 'string',
      label: 'Background Color',
      default: '#CECECE',
      section: 'Style',
      display: 'color',
      order: 20,
    },
    bar_spinner_color: {
      type: 'string',
      label: 'Pointer Color',
      default: '#282828',
      section: 'Style',
      display: 'color',
      order: 30,
    },
    bar_range_color: {
      type: 'string',
      label: 'Range Label Color',
      default: '#282828',
      section: 'Style',
      display: 'color',
      order: 40,
    },
  },
};
